export const PLAYERS_ACTION_TYPE = {
  FATCH_PLAYERS_DATA_SUCCESS: "players/FATCH_PLAYERS_DATA_SUCCESS",
  FATCH_PLAYERS_DATA_FAILED: "players/FATCH_PLAYERS_DATA_FAILED",
  FATCH_PLAYER_DATA_SUCCESS: "players/FATCH_PLAYER_DATA_SUCCESS",
  FATCH_PLAYER_DATA_FAILED: "players/FATCH_PLAYER_DATA_FAILED",
  FATCH_PLAYER_INFO_DATA_SUCCESS: "players/FATCH_PLAYER_INFO_DATA_SUCCESS",
  FATCH_PLAYER_INFO_DATA_FAILED: "players/FATCH_PLAYER_INFO_DATA_FAILED",
  FATCH_PLAYER_BATTING_STATE_DATA_SUCCESS:
    "players/FATCH_PLAYER_BATTING_STATE_DATA_SUCCESS",
  FATCH_PLAYER_BATTING_STATE_DATA_FAILED:
    "players/ FATCH_PLAYER_BATTING_STATE_DATA_FAILED",
  FATCH_PLAYER_BOWLING_STATE_DATA_SUCCESS:
    "players/FATCH_PLAYER_BOWLING_STATE_DATA_SUCCESS",
  FATCH_PLAYER_BOWLING_STATE_DATA_FAILED:
    "players/ FATCH_PLAYER_BOWLING_STATE_DATA_FAILED",
  SET_PLAYER_SEARCH_STRING: "players/SET_PLAYER_SEARCH_STRING",
  SET_PLAYER_FILTER_OPTION: "players/SET_PLAYER_FILTER_OPTION",
};
