export const TEAMS_ACTION_TYPE = {
  FATCH_TEAMS_DATA_SUCCESS: "teams/FATCH_TEAMS_DATA_SUCCESS",
  FATCH_TEAMS_DATA_FAILED: "teams/FATCH_TEAMS_DATA_FAILED",
  FATCH_TEAM_DATA_SUCCESS: "teams/FATCH_TEAM_DATA_SUCCESS",
  FATCH_TEAM_DATA_FAILED: "teams/FATCH_TEAM_DATA_FAILED",
};
